workflows:
  react-native-android:
    name: CreatorBoost AI Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo
      vars:
        EXPO_PUBLIC_GEMINI_API_KEY: "AQ.Ab8RN6K2ONp2ZPbrnUlYH1SVRNWfmsPn_oDTvkOYv_7_-UBq5w"
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Build Android APK
        script: |
          npx expo export
          npx expo run:android --variant release --no-dev
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
